name: TG to VK Repost
on:
  schedule:
    - cron: '*/15 * * * *'  # Проверка каждые 15 минут
  workflow_dispatch:  # Ручной запуск

jobs:
  repost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Установка зависимостей
        run: |
          pip install python-telegram-bot vk_api

      - name: Запуск скрипта
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
        run: python main.py
